plugins/behaviors.py
plugins/commands.py
requirements.txt

Python modules were updated and some changes were necessary regarding asyncio and
aiohttp modules on custom plugins in order to make them work again.

plugins: update asyncio and aiohttp interfaces on custom plugins

---

Pipfile
Pipfile.lock
requirements.txt

Just refactoring the project to use PipFile (pipenv) insted of normal `requirements.txt` files.

Add PipFile

---

migrations/env.py
migrations/versions/754804413f2a_create_greetings_table.py
mr_roboto.py
plugins/behaviors.py
plugins/commands.py

Corrected flake8 warnings on all .py files on this project.
Partially solves issue #21.

Fix coding style following flake8 standards

---

migrations/env.py
migrations/versions/56fab68d28b9_create_url_history_table.py
migrations/versions/754804413f2a_create_greetings_table.py
mr_roboto.py
plugins/__init__.py
plugins/behaviors.py
plugins/commands.py
plugins/database.py

Resolves coding style issues according to #21.

Adjusts coding style

---

plugins/commands.py

Fixes **!horoscope** command by switching its API and performing some minor changes to the code in order to adapt to the new resource.
Solves part of the issue #33.

Fixes horoscope command

---

test/test_database.py

Adds test for Database plugin.

---

test/conftest.py

This fixture fakes a irc3bot instance to avoid creating one on every test.

Adds bot fixture

---

test/test_baseplugin.py
test/test_database.py
test/test_mr_roboto.py

Applies bot's fixture to the existing tests.

Applies fixture

---

plugins/behaviors.py

Fixes **lxml** ParserError when trying to create an html object from an empty string.

Fixes lxml ParserError

---

Pipfile
Pipfile.lock
test/conftest.py
test/test_behaviors.py

Requires the patches of PR #47 and #48 to be applied in order to run properly.
Solves part of the issue #23.

Add tests for Behaviors plugin

---

plugins/commands.py

Not so important but in order to make this method easier to test a normal output is better.

Normalises urls method output

---

test/conftest.py
test/test_commands.py

Requires the patch of PR #50 to be applied in order to run properly.
Solves part of the issue #23.

Add tests for Commands plugin

---

test/test_config.py

Adds missing test for configuration file.
Solves part of the issue #23.

Add tests for the Config class

---

migrations/versions/e88a6b58cdc6_create_slackers_table.py
plugins/behaviors.py
plugins/commands.py
test/conftest.py
test/test_behaviors.py
test/test_commands.py

The new feature brings two updates:
1. (**plugins.behaviors**) Counts every word said by everyone and stores it;
2. (**plugins.commands**) Provides a command that prints a slackers rank.

Adds new feature slackers

---

migrations/versions/ee3de573220a_create_karma_table.py
plugins/behaviors.py
plugins/commands.py
test/conftest.py
test/test_behaviors.py
test/test_commands.py

The new feature brings two updates:
1. (**plugins.behaviors**) Identifies when someone sends a karma update request (e.g. python++);
2. (**plugins.commands**) Provides a command that list the channel's karma statuses.
Solves issue #4.

Adds new feature Karma

---

plugins/commands.py
test/test_commands.py

The new command just prints the following message:
> Hi there, my name is **bot.nick** and I am an IRC bot written in Python. If you wanna know more about me take a look at my Github page https://github.com/meleca/mr-roboto/.
Closes issue #11.

Adds new command about

---

Makefile
mr_roboto.py
plugins/commands.py
test/conftest.py
test/test_commands.py
test/test_mr_roboto.py

Set version number on Makefile and retrieve its value on mr_roboto source code
to let available to the whole code base through bot instance.
It solves issue #64.

Makefile: add bot version number

---

.pyup.yml

Configures pyup to send updates as soon as they were released.

Updates pyup configuration

---

.pyup.yml

Schedule weekly updates

---

i18n/catalog.py

Translate to Portuguese
